### ISSUE TITLE
Consider the names of functions

### ISSUE THREAD

**Issue by adamhsparks** [DPIRD-FSI/weatherOz#21]
I'm considering whether the current function names are what we need or if we could clarify them further.

Prefixing the functions that only deal with BOM, SILO or DPIRD data could clarify for users where the data comes from. But it may not matter either.

Currently, we have `get_datasource_data()` and `get_data()` both in the package. Is it necessary to include the extra chars for the data source or can we shorten the function names, _e.g._ `get_summaries()`, `get_minute()`. Alternatively, we could prefix the data source, which might make the fn names longer but easier to scan and find what you're looking for.

**Comment by arhepworth** [comment]
I think that naming scheme is an artefact from the original SFF code, where the functions for querying the DPIRD and SILO data sets were quite different; this is why there was a generic `get_weather()` (or similar) which was a wrapper to the two internal functions. Where we do have data source specific functions, I'm inclined to keep that, but I'm not strongly attached to the idea. I agree that moving it to the front of the name makes more sense, if we decide to keep it.

**Comment by arhepworth** [comment]
I've had a look through the names, they all look clear to me.

**Comment by adamhsparks** [comment]
Closing this issue to prep for first release. Function names appear to be clear enough since there was no further discussion.
