### ISSUE TITLE
Having trouble retrieving data

### ISSUE THREAD

**Issue by dicook** [DPIRD-FSI/weatherOz#26]
**Describe the bug**
I'm trying to use `get_dpird_minute()`, but regardless of the options that I use it returns an error:

`Error in .parse_minute(.ret_list = return_list) : object 'out' not found`

**To Reproduce**
`x <- get_dpird_minute("SP", api_key = "MYKEY")`

`x <- get_dpird_minute("SP", values = "solarIrradiance", api_key = "MYKEY")`

`x <- get_dpird_minute("SP", start_date_time = ymd_hm("2023/06/29 06:00"), minutes = 360, api_key ="MYKEY")`

**Expected behavior**
I would expect that x is populated with whatever data is available from the given station

**Laptop (please complete the following information):**
 - OS: OSX
 - Version: R version 4.3.1 (2023-06-16) -- "Beagle Scouts", weatherOz 0.0.0.9000

**Additional context**
The list of stations returned by `find_nearby_stations()` when searching around Perth is different from `get_station_metadata()` and the station id's don't match, for example "SP" is not a station returned by `find_nearby_stations()`, which does not seem to return id's that are recognised as stations by the other functions.

**Comment by adamhsparks** [comment]
Thanks, @dicook, I've fixed the first part, you can fetch minute data (again). https://github.com/DPIRD-FSI/weatherOz/commit/f8a03e9f9d6e115e1926d27448f7441ee5451b5e, I'll look into the other functions. Right now I'm cleaning up the `find_nearby_stations()` function in another branch.

**Comment by dicook** [comment]
Data download is working nicely!

**Comment by adamhsparks** [comment]
@dicook, can you please check the metadata and nearby stations' returns now? I *think* that I've managed to wrangle this one now too. It's all related to issues merging data sets from SILO and BOM to get the complete metadata.

**Comment by adamhsparks** [comment]
I've managed to get an example where `find_nearby_stations()` and `get_station_metadata()` list different stations.

```r
library(weatherOz)

 me_stn <- find_nearby_stations(
   station_code = "ME",
   distance_km = 10,
   api_key = Sys.getenv("DPIRD_API_KEY"),
   which_api = "all"
 )

stn_meta <- get_station_metadata(api_key = Sys.getenv("DPIRD_API_KEY"))
```

`stn_meta` will not contain station "010093" in it.

**Comment by adamhsparks** [comment]
Whoops, `get_station_metadata()` does work as expected. The bug is in `find_nearby_stations()`. The station 010093 closed in 2015, so this:

```r
stn_meta <- get_station_metadata(api_key = Sys.getenv("DPIRD_API_KEY"), include_closed = TRUE)
```

Will return that metadata.

`find_nearby_stations()` appears to be ignoring the `include_closed = FALSE` default value.

**Comment by adamhsparks** [comment]
Will close this and open a new issue for `find_nearby_stations()`
