### ISSUE TITLE
`find_forecast_towns` doesn't apply `distance_km` parameter

### ISSUE THREAD

**Issue by nwbort** [DPIRD-FSI/weatherOz#35]
**Describe the bug**

`find_forecast_towns` returns the same results regardless of the value of the `distance_km` parameter.

**To Reproduce**

Execute:

```
library(weatherOz)
find_forecast_towns(longitude = 149.2, latitude = -35.3, distance_km = 100)
```

Actual behaviour:
A `data.table` with 1475 rows, including forecast towns further away from the point than 100km.

**Expected behavior**
Return `data.table` with 24 rows, being the forecast towns no further away than 100km from the point.

**Desktop:**
- Version: `weatherOz_0.0.1`
 - OS: Windows 11

**Comment by adamhsparks** [comment]
thank you!
