### ISSUE TITLE
Curl Error when calling get_dpird_summaries

### ISSUE THREAD

**Issue by 16-inch-carp** [DPIRD-FSI/weatherOz#38]
**Describe the bug**
Running this reprex 

```
library(weatherOz)

wd <- get_dpird_summaries(
  station_code = "BD002",
  start_date = "20200406",
  end_date = "20221231",
  api_key = Sys.getenv("DPIRD_API_KEY"),
  interval = "daily",
)
```
results in the following error:

> Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) :
> Failure when receiving data from the peer

**Desktop (please complete the following information):**
 - OS: Windows 10
 - weatherOz Version: weatherOz_0.0.1.9000
- R Version: 4.3.1

**Comment by adamhsparks** [comment]
Thanks for reporting this. I've confirmed it and we are looking into it.

**Comment by adamhsparks** [comment]
I've isolated the issue. Though I'm unsure why it's occurring. I hope to have a fix for it soon.

**Comment by adamhsparks** [comment]
We've determined that this is a server-side configuration issue. I'm attempting to get someone who can fix it to take a look as this isn't in our area.

**Comment by adamhsparks** [comment]
I've implemented a temporary fix in this commit. https://github.com/DPIRD-FSI/weatherOz/commit/7c542ffdffef6aab79883fe839aed74500e3aef8
