### ISSUE TITLE
`plot` should not be a weatherOz function; rename or remove

### ISSUE THREAD

**Issue by arhepworth** [DPIRD-FSI/weatherOz#6]
loading the package gets

```
> library(weatherOz)

Attaching package: ‘weatherOz’

The following object is masked from ‘package:graphics’:

    plot

The following object is masked from ‘package:base’:

    plot
```

**Comment by adamhsparks** [comment]
This is intended but may change. Please see the docs, https://dpird-fsi.github.io/weatherOz/articles/weatherOz.html#using-get_satellite_imageryOn 28 Mar 2023, at 14:17, arhepworth ***@***.***> wrote:﻿
loading the package gets
> library(weatherOz)

Attaching package: ‘weatherOz’

The following object is masked from ‘package:graphics’:

    plot

The following object is masked from ‘package:base’:

    plot
