### ISSUE TITLE
Function arguments are inconsistent

### ISSUE THREAD

**Issue by adamhsparks** [DPIRD-FSI/weatherOz#8]
`get_dpird_summaries()` takes dates as "yyyy-mm-dd" while `get_silo()` takes dates as "yyyymmdd".

These should be a standard format across all functions in the package.

**Comment by bozaah** [comment]
`.check.date()` has the functionally we need. I have maintained "yyyymmdd" date format from `get_silo()`.
I have also added Sys.timezone() as an argument to `.check_date()`. Commit [7784f9d](https://github.com/DPIRD-FSI/weatherOz/commit/7784f9d2b6f156913516fe9890dfb531cc759ca3) fix this issue.
